from .index import router as index_router
from .customers import router as customers_router
from .orders import router as orders_router
from .order_details import router as order_details_router
from .payments import router as payments_router
from .promotions import router as promotions_router
from .reviews import router as reviews_router
from .recipes import router as recipes_router
from .resources import router as resources_router
from .sandwiches import router as sandwiches_router
